[build]
  base = "cityswipe-fe"
  command = "pnpm exec prisma generate && pnpm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22"

[[plugins]]
  package = "@netlify/plugin-nextjs"
