import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import GameProvider from "./match/_components/gameContext";
import { getGame } from "./match/_components/games.api";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const game = await getGame(0);
  return (
    <html lang="en">
      <body className={inter.className}>
        <GameProvider game={game}>{children}</GameProvider>
      </body>
    </html>
  );
}
