import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { CitySwipeProvider } from './citySwipeContext';
import "./globals.css";
import GameProvider from "./match/_components/gameContext";
import { getGame } from "./match/_components/games.api";
import DestinationProvider from "./match/_components/destinationContext";
import { getDestination } from "./match/_components/destination.api";
import { Analytics } from '@vercel/analytics/react';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const game = await getGame(0);
  const destination = await getDestination();
  return (
    <html lang="en">
      <body className={inter.className}>
      <Analytics />
        <CitySwipeProvider>
          <DestinationProvider destination={destination}>
            <GameProvider game={game}>{children}</GameProvider>
          </DestinationProvider>
        </CitySwipeProvider>
      </body>
    </html>
  );
}
